target 'Smooth' do
  use_modular_headers!

  pod 'Charts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FacebookShare'
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'SwiftyJSON', '~> 4.0'
end
